---
- name: Install Required Software
  hosts: localhost
  become: no  # Run tasks with sudo

  tasks:
    - name: Enable nginx service
      command: sysrc -f /etc/rc.conf nginx_enable=YES
      become: yes

    - name: Install pnpm using npm
      command: npm install -g pnpm
      become: yes

    - name: Download and install Go 1.22.0
      command: go install golang.org/dl/go1.22.0@latest
      become: yes

    - name: Download Go dependencies
      command: /root/go/bin/go1.22.0 download
      become: yes

    - name: Create symbolic links for Go binaries
      command: ln -s /root/sdk/go1.22.0/bin/{{ item }} /usr/local/bin/{{ item }}122
      with_items:
        - go
        - gofmt
      become: yes

    - name: Fetch nginx-ui source code
      command: fetch https://github.com/0xJacky/nginx-ui/archive/refs/tags/v2.0.0-beta.14.tar.gz
      become: yes

    - name: Extract nginx-ui source code
      command: tar -xf v2.0.0-beta.14.tar.gz
      become: yes

    - name: Rename nginx-ui directory
      command: mv nginx-ui-2.0.0-beta.14 nginx-ui
      become: yes

    - name: Apply sed command to package.json
      command: sed -i .bak '1 r /root/fix_package_json.sed' package.json
      args:
        chdir: /root/nginx-ui/app
      become: yes

    - name: Install dependencies
      command: pnpm install
      args:
        chdir: /root/nginx-ui/app
      become: yes

    - name: Build UI
      command: pnpm build
      args:
        chdir: /root/nginx-ui/app
      become: yes

    - name: Build nginx-ui with Go
      command: go122 build -o nginx-ui -v main.go
      args:
        chdir: /root/nginx-ui
      become: yes

    - name: Copy app.example.ini to app.ini
      command: cp app.example.ini /usr/local/etc/nginx_ui_app.ini
      args:
        chdir: /root/nginx-ui
      become: yes

    # - name: Start nginx-ui service
    #   command: nginx-ui -config app.ini
    #   args:
    #     chdir: /root/nginx-ui
    #   become: yes

    - name: Enable nginx-ui service
      command: sysrc -f /etc/rc.conf nginx_ui_enable=YES
      become: yes

    # - name: Fix site-available/enable folders in Nginx
    #   command: bsd-nginx-sites/nginx-sites.sh
    #   args:
    #     chdir: /root
    #   become: yes

    # - name: Add nginx-ui Nginx virtual server config
    #   command: cp nginxui.conf /usr/local/etc/nginx/site-available/
    #   args:
    #     chdir: /root
    #   become: yes

    # - name: Add recomended proxy params
    #   command: cp proxy_params /usr/local/etc/nginx/
    #   args:
    #     chdir: /root
    #   become: yes

    # - name: Enable nginx-ui site
    #   command: ln -s nginxui.conf /usr/local/etc/nginx/sites-available/nginxui.conf /usr/local/etc/nginx/sites-enabled/
    #   args:
    #     chdir: /root
    #   become: yes

    - name: Start nginx service
      command: service nginx start 
      become: yes

    - name: Start nginx-ui service
      command: service nginx-ui start 
      become: yes
